cluster.name: full-stack-cluster
node.name: node-1
path.data: /usr/share/elasticsearch/data
http.port: 9200
network.host: 0.0.0.0

discovery.zen.minimum_master_nodes: 1
xpack.license.self_generated.type: trial

xpack.monitoring.enabled: true
xpack.monitoring.exporters.es_local:
  type: local
