openapi: '3.0.0'
info:
  version: 1.0.0
  title: Market Data API
tags:
  - name: "market-data"
    description: "Access to market data"
paths:
  /quotes:
    get:
      summary: Get current quotes
      operationId: getQuotes
      tags:
        - quotes
      responses:
        '200':
          description: The current quotes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quote'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /quotes/{stock}:
    get:
      summary: Get current quote of specific stock
      operationId: getQuote
      tags:
        - quotes
      parameters:
        - name: stock
          in: path
          required: true
          description: The name of the stock
          schema:
            type: string
      responses:
        '200':
          description: The current quote of requested stock
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
        '404':
          description: Requested resource could not be found
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Quote:
      description: Representation of a quote.
      required:
        - name
        - price
      properties:
        name:
          description: Name of the corresponding stock
          readOnly: true
          type: string
        price:
          description: Current stock price
          readOnly: true
          type: double
        quoteTime:
          description: The date and time the quote was created.
          readOnly: true
          type: string
          format: date-time
      additionalProperties: false
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT